### ISSUE TITLE
Download Asset in Craft CMS Control Panel

### ISSUE THREAD

**Issue by NateAtHarvest** [fortrabbit/craft-object-storage#12]
Hello,

When seeking to download a file stored in object storage via the craftCMS cp asset download button, it attempts to use the Base URL of the site instead of the object storage Base URL.  Is this an issue with FortRabbit or CraftCMS?

<img width="388" alt="Screen Shot 2020-12-08 at 4 12 24 PM" src="https://user-images.githubusercontent.com/75700322/101542027-2c764180-3970-11eb-8b51-5f6bf24a2b44.png">

**Comment by ostark** [comment]
@NateAtHarvest Can you share your Volume config?

**Comment by NateAtHarvest** [comment]
@ostark - Sorry for the delayed response.  Here you go:

<img width="814" alt="Screen Shot 2020-12-11 at 5 30 37 PM" src="https://user-images.githubusercontent.com/75700322/101960950-9db72e00-3bd6-11eb-951a-0eb34b9a4c4f.png">

And..... the .env file

<img width="646" alt="Screen Shot 2020-12-11 at 5 32 16 PM" src="https://user-images.githubusercontent.com/75700322/101961027-d6570780-3bd6-11eb-9d21-defa9ffe0fa0.png">

And, here is a screen shot of the url path it tries to use... it uses the website's url path....
<img width="455" alt="Screen Shot 2020-12-11 at 5 34 22 PM" src="https://user-images.githubusercontent.com/75700322/101961198-32219080-3bd7-11eb-85c0-7d7bceb10687.png">

**Comment by ostark** [comment]
Sorry Nate, I wasn't able to reproduce this.
