### ISSUE TITLE
Cannot install on Craft 3.6.5.1 – bump down `require`?

### ISSUE THREAD

**Issue by blieque** [fortrabbit/craft-object-storage#14]
I'm not able to install craft-object-storage 2.0.0 on Craft 3.6.5.1 via the Craft web UI. I'm hosting Craft in a Docker container and don't have access to a shell on the server. Even if I did, I don't think shell access should be required for this.

The error stems from craft-object-storage's [requirement for PHP 7.3+](https://github.com/fortrabbit/craft-object-storage/blob/master/composer.json#L22), and [Craft 3.x's `"platform": { "php": "7.2.5" }` setting](https://github.com/craftcms/cms/blob/develop/composer.json#L90). This has been [changed in Craft 4.x](https://github.com/craftcms/cms/blob/4.0/composer.json#L90), so presumably the plugin would install, but I don't want to use a pre-release version of Craft. Shell access would allow me to run Composer manually with the `--ignore-platform-reqs` argument, but this isn't an option.

Does craft-object-storage *actually* depend on PHP 7.3+? Can this `require` version be bumped down, or is this Craft's problem?

**Comment by ostark** [comment]
The latest version of the plugin requires PHP 7.3 and Craft 3.5.

Which php version do you actually run in your docker container? I assume > 7.2. 
I'd recommend to remove the fake version from your composer.json.

If you really use PHP 7.2 or lower you can use the 1.* branch.

**Comment by blieque** [comment]
Thanks for the quick reply!

Yeah, the actual version of PHP is newer (7.3.22), but the `platform` configuration from Craft is picked up by Composer. The Docker container currently just pulls the latest version of Craft 3.x when it's built. It's relatively generic, so I don't have a `composer.json` checked-in. I could modify the file during build, but that would be likely to break in the future. It's a bit of an unusual deployment, I'll grant you.

If craft-object-storage 2.0.0 doesn't work on PHP 7.2, then close this and I'll file an issue with the CMS. That said, out-of-the-box, this plugin doesn't install on Craft 3.6.5.1. 

Package | Version
|:-|-:|
PHP | 7.3.22
MySQL | 5.5.5
GD | 7.3.22
Craft | Solo 3.6.5.1
Yii | 2.0.40
