### ISSUE TITLE
AWS PHP SDK bug

### ISSUE THREAD

**Issue by pixelmachine** [fortrabbit/craft-object-storage#15]
Hi, the issue https://github.com/aws/aws-sdk-php/issues/2209 is currently breaking the plugin.

I had to downgrade AWS as per https://github.com/thephpleague/flysystem-aws-s3-v3/issues/250#issuecomment-803580076 for the object storage to connect from Craft.

**Comment by ostark** [comment]
Untested so far:

```
composer require fortrabbit/craft-object-storage:dev-hotfix/fix-aws-sdk-dependency
```

**Comment by ostark** [comment]
This fix 👆️ is probably not needed once this is released: https://github.com/aws/aws-sdk-php/pull/2214
