### ISSUE TITLE
Volume settings stored as plain text (in DB and Project Config)

### ISSUE THREAD

**Issue by appslt** [fortrabbit/craft-object-storage#2]
## Description

When setting up volumes, their settings (including passwords/secrets) get stored as plain text in the DB as well as in the Project Config YAML file (a new feature in Craft 3.1) although I am using the .ENV vars in volumes.php. I guess this is related or similar to this issue here: https://github.com/craftcms/cms/issues/3531

Is there any chance that the plugin will provide environment variable support soon?

## Additional info

- PHP version: 7.2
- Craft version: 3.1.5

**Comment by ostark** [comment]
@appslt Thanks for the reminder! That's on our list already.

**Comment by appslt** [comment]
@ostark Cool, thanks for the info. And sorry for raising the issue then, I wasn't aware that it's on your list already.

**Comment by ostark** [comment]
It might be related to https://github.com/craftcms/aws-s3/issues/35 - not sure if we can support it before it is fixed in core.

**Comment by jamesmacwhite** [comment]
@ostark I'm coming at this from a slightly different angle. My organisation is hosted on Fort Rabbit but we use our own S3 storage. I've used the `config/volumes.php` as a template to setup S3 volumes in Craft 3, which works fine. The one thing that I'm not sure about is the whole use of `secrets.json` on the Fort Rabbit environment with values like the `keyId`, `secret` and does this prevent `project.yaml` from "seeing" the values if they were referenced like so:

```
if($secrets = json_decode(file_get_contents($file), true))
{
    $s3Creds = [
        'url' => getenv('UPLOAD_ASSET_BASE_URL'),
        'keyId' => $secrets['CUSTOM']['AWS_ACCESS_KEY'],
        'secret' => $secrets['CUSTOM']['AWS_SECRET_ACCESS_KEY'],
        ...
	];
}
...

return [
// Volume handles
]
```

**Comment by ostark** [comment]
Eventually added Craft::parseEnv() support for `keyId` and `secret` to prevent storing credentials in the DB and project config: https://github.com/fortrabbit/craft-object-storage/releases/tag/1.1.0
