### ISSUE TITLE
Dynamic subfolders

### ISSUE THREAD

**Issue by millman2394** [fortrabbit/craft-object-storage#3]
I'd like to organize assets depending on an entry. For instance, I have a channel called "Locations" and i'd like each of them to have a subfolder in /locations

`assets/uploads/locations/san-diego`
`assets/uploads/locations/san-francisco`

etc

is this possible?

**Comment by ostark** [comment]
Not directly related to the plugin or the object storage. Craft will fully support this in 3.2
https://github.com/craftcms/cms/issues/4010
